//
//  Theme.swift
//  SaltScan
//
//  Design system tokens: colors, spacing, radii, shadows, typography.
//

import SwiftUI

// MARK: - Spacing

enum SSSpacing {
    static let xxs: CGFloat = 4
    static let xs: CGFloat = 8
    static let sm: CGFloat = 12
    static let md: CGFloat = 16
    static let lg: CGFloat = 24
    static let xl: CGFloat = 32
    static let xxl: CGFloat = 48
}

// MARK: - Radius

enum SSRadius {
    static let sm: CGFloat = 12
    static let md: CGFloat = 20
    static let lg: CGFloat = 28
    static let pill: CGFloat = 999
}

// MARK: - Shadow

struct SSShadow {
    let color: Color
    let radius: CGFloat
    let x: CGFloat
    let y: CGFloat

    static let soft = SSShadow(color: .black.opacity(0.08), radius: 12, x: 0, y: 4)
    static let elevated = SSShadow(color: .black.opacity(0.14), radius: 22, x: 0, y: 10)
}

extension View {
    func ssShadow(_ shadow: SSShadow = .soft) -> some View {
        self.shadow(color: shadow.color, radius: shadow.radius, x: shadow.x, y: shadow.y)
    }
}

// MARK: - Typography

enum SSFont {
    static func largeTitle() -> Font { .system(.largeTitle, design: .rounded, weight: .bold) }
    static func title() -> Font { .system(.title, design: .rounded, weight: .bold) }
    static func title2() -> Font { .system(.title2, design: .rounded, weight: .semibold) }
    static func title3() -> Font { .system(.title3, design: .rounded, weight: .semibold) }
    static func headline() -> Font { .system(.headline, design: .rounded, weight: .semibold) }
    static func body() -> Font { .system(.body, design: .rounded) }
    static func subheadline() -> Font { .system(.subheadline, design: .rounded) }
    static func caption() -> Font { .system(.caption, design: .rounded) }
    static func monoNumber() -> Font { .system(.title2, design: .rounded, weight: .bold).monospacedDigit() }
}

// MARK: - Colors

extension Color {
    /// Brand primary — health green.
    static let ssPrimary = Color(red: 0.18, green: 0.72, blue: 0.52)
    /// Brand accent — deep teal.
    static let ssAccent = Color(red: 0.09, green: 0.44, blue: 0.52)

    /// Severity palette — low salt (green), medium (orange), high (red).
    static let ssSeverityLow = Color(red: 0.22, green: 0.74, blue: 0.45)
    static let ssSeverityMedium = Color(red: 0.96, green: 0.64, blue: 0.20)
    static let ssSeverityHigh = Color(red: 0.93, green: 0.33, blue: 0.33)

    /// Nutriscore palette (A..E).
    static let ssNutriA = Color(red: 0.16, green: 0.62, blue: 0.34)
    static let ssNutriB = Color(red: 0.52, green: 0.76, blue: 0.24)
    static let ssNutriC = Color(red: 0.99, green: 0.80, blue: 0.18)
    static let ssNutriD = Color(red: 0.96, green: 0.55, blue: 0.18)
    static let ssNutriE = Color(red: 0.90, green: 0.27, blue: 0.23)

    // Surfaces are provided by the asset catalog (Assets.xcassets/Colors/
    // ssBackground, ssGroupedBackground, ssSurface, ssSurfaceElevated) and
    // auto-generated by Xcode as `Color.ssBackground`, etc. No static
    // redeclaration is needed here.

    /// Text — SwiftUI semantic colors.
    static let ssTextPrimary = Color.primary
    static let ssTextSecondary = Color.secondary
    static let ssTextTertiary = Color.secondary.opacity(0.6)
}
// Note: `cardBackground` / `cardOver` remain defined in Utils/ColorsManager.swift
// for backward compatibility with pre-refresh screens.

// MARK: - Severity

enum SSSeverity {
    case low, medium, high

    var color: Color {
        switch self {
        case .low: .ssSeverityLow
        case .medium: .ssSeverityMedium
        case .high: .ssSeverityHigh
        }
    }

    var iconName: String {
        switch self {
        case .low: "arrow.down.forward.circle.fill"
        case .medium: "arrow.right.circle.fill"
        case .high: "arrow.up.forward.circle.fill"
        }
    }

    var localizedLabelKey: LocalizedStringKey {
        switch self {
        case .low: "ds.severity.low"
        case .medium: "ds.severity.medium"
        case .high: "ds.severity.high"
        }
    }

    /// Classify from salt (g / 100g), per standard food labelling thresholds.
    static func fromSaltPer100g(_ saltG: Double) -> SSSeverity {
        if saltG > 1.5 { .high }
        else if saltG >= 0.5 { .medium }
        else { .low }
    }

    /// Classify from sodium (g / 100g) by converting to salt (×2.5).
    static func fromSodiumPer100g(_ sodiumG: Double) -> SSSeverity {
        fromSaltPer100g(sodiumG * 2.5)
    }
}
